version: '3.9'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: MongoDB
    volumes:
      - ./.mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  crawler:
    image: antonio/crawler
    build: .
    restart: always
    container_name: crawler
    volumes:
      - .:/workspace

