apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-crawler
  labels:
    app: crawler
data: 
  MONGO_DB_URI : "mongodb://foo:mustbeeightchars@weather-scanner-nlb-ad65dd6f7883376f.elb.eu-west-1.amazonaws.com:27017/weather_scanner?tls=true&retryWrites=false&tlsInsecure=true&directConnection=true"
  SNS_TOPIC : 'arn:aws:sns:us-east-1:116695809482:weather-daily-notifications'
